carb_subs = {
	'bread':'wheat bread',
	'white bread':'wheat bread',
	'milk':'soy milk',
	'whole milk':'soy milk',
	'potatoes':'squash',
	'sweet potatoes':'squash',
	'cheese':'cottage cheese',
	'pasta':'whole what pasta',
	'bun':'lettuce wrap bun',
	'french fries':'squash fries',
	'biscuits':'whole wheat biscuits',
	'crackers':'carrots',
	'yogurt':'low-fat yogurt',
	'butter':'olive oil',
	'chips':'carrots',
	'potato chips':'carrots',
	'beans':'soy beans',
	'flour':'whole wheat flower',
	'pizza crust':'mushroom pizza crust',
	'tortillas':'low-carb tortillas',
	'cereal':'oatmeal',
	'hamburger bun':'lettuce bun',
	'tacos':'lettuce wraps',
	'bruschetta toast':'roasted eggplant bread',
	'chickpeas':'soy beans',
	'bisquik':'carbquik',
}