fat_subs = {
	'salted':'unsalted',
	'beef':'lean beef',
	'bread':'whole wheat bread',
	'white bread':'low-fat white bread',
	'chicken':'lean skinned chicken',
	'bacon':'canadian bacon',
	'fudge':'low-fat syrup',
	'ground beef':'ground turkey',
	'sour cream':'yogurt',
	'potato':'squash',
	'cheese':'low-fat cheese',
	'cheddar cheese':'low-fat cheddar cheese',
	'mozzarella cheese':'low-fat mozzarella cheese',
	'pasta':'whole what pasta',
	'bun':'lettuce wrap bun',
	'french fries':'squash fries',
	'biscuits':'whole wheat biscuits',
	'crackers':'carrots',
	'yogurt':'low-fat yogurt',
	'butter':'olive oil',
	'chips':'carrots',
	'potato chips':'carrots',
	'beans':'soy beans',
	'flour':'whole wheat flower',
	'pizza crust':'mushroom pizza crust',
	'tortillas':'low-carb tortillas',
	'cereal':'oatmeal',
	'hamburger bun':'lettuce bun',
	'tacos':'lettuce wraps',
	'bruschetta toast':'roasted eggplant bread',
	'chickpeas':'soy beans',

}