# Matches a Method to Required Tools
methodToTools = {
	"cut": "knife",
	"cutting": "knife",
	"chop": "knife",
	"chopping": "knife",
	"mince": "knife",
	"minced": "knife",
	"mincing": "knife",
	"slice": "knife",
	"sliced": "knife",
	"slicing": "knife",
	"dice": "knife",
	"diced": "knife",
	"dicing": "knife",
	"cube": "knife",
	"cubed": "knife",
	"cubing": "knife",
	"bake": "oven",
	"baked": "oven",
	"baking": "oven",
	"microwave":"microwave",
	"microwaved":"microwave",
	"microwaving":"microwave",
	"baste":"baster",
	"basted":"baster",
	"basting":"baster",
	"grate":"grater",
	"grated":"grater",
	"grating":"grater",
	"shred":"grater",
	"shredding":"grater",
	"shredded":"grater",
	"measure":"measuring cups",
	"measured":"measuring cups",
	"measuring":"measuring cups",
	"peel":"peeler",
	"peeled":"peeler",
	"peeling":"peeler",
	"core":"paring knife",
	"cored":"paring knife",
	"pare":"paring knife",
	"pared":"paring knife",
	"paring":"paring knife",
	"blend":"electric mixer",
	"blended":"electric mixer",
	"blending":"electric mixer",
	"skewer": "barbecue fork",
	"skewered": "barbecue fork",
	"skewering": "barbecue fork",
	"strain": "strainer",
	"straining": "strainer",
	"glaze": "pastry brush",
	"glazed": "pastry brush",
	"glazing": "pastry brush",
	"stir":"wooden spoon",
	"stirred":"wooden spoon",
	"stirring":"wooden spoon",
	"beat": "whisk",
	"beating": "whisk",
	"spoon":"spoon"

}


def method2tool(method):
	if method in methodToTools:
		return methodToTools[method]
	else:
   		return None


##General list of tools that a step might include
toolslist = [
"spatula",
"knife",
"cooker",
"pan",
"yogurt maker",
"peeler",
"cube tray",
"strainer",
"fruit muddler",
"freezer tray",
"plate",
"fry pan",
"cake pan",
"foil",
"cuisinart",
"grinder",
"mincer",
"hullster",
"shaker",
"grate and slice set",
"scale",
"measuring cups",
"spoon",
"fork",
"press",
"whisk",
"skimmer",
"tongs",
"potato masher",
"soup ladle",
"brush",
"an opener",
"juicer press",
"floor sifter",
"pizza wheel",
"tea ball",
"pepper grinder",
"salt shaker",
"grater",
"corkscrew",
"lid",
"bowl",
"measuring cup",
"utensil",
"egg topper",
"cheese slicer",
"scoop",
"skimmer",
"strainer",
"serve ladle",
"saute spoon",
"cutting board",
"spill stopper",
"splatter screen",
"burner",
"egg beater",
"potato ricer",
"food mill",
"grater",
"peeler",
"slicer",
"stripper",
"corn zipper",
"shear",
"snips",
"chopper",
"mandoline",
"mortar",
"pestle",
"can",
"mister",
"seal",
"stopper",
"pourer",
"scale",
"timer",
"thermometer",
"board",
"cloth",
"parchment roll",
"aluminium foil",
"cupcake liners",
"decorating pen",
"muffin papers",
"baking cups",
"baking pan",
"bags",
"smoother",
"sieve",
"wheel",
"shield",
"blender",
"scraper",
"lifter",
"gloves",
"rack",
"rolling pin",
"skewer",
"wrangler",
"oven",
"microwave",
"lighter",
"probe",
"rack",
"saucepan",
"baking dish",
"plastic bag",
"paper warp",
"pan",
"dish",
"skillet",
"casserole",
"mixing bowl",
"frying pan",
"baking sheet",
"absinthe spoon",
"adjustable V-rack",
"aluminum foil",
"aluminum stock pan",
"anodized aluminum nonstick pan",
"apple corer",
"apple cutter",
"auto reignition",
"bachelor griller",
"bamboo stove",
"bar spoon",
"barbecue",
"barbecue grill",
"basket rack",
"baster",
"beehive oven",
"berry spoon",
"big green egg",
"biscuit cutter",
"biscuit press",
"blow torch",
"boil over preventer",
"baking pan",
"baking sheets",
"baking stone",
"beanpot",
"bedrock mortar",
"bottle opener",
"bottle scraper",
"bowl",
"braiser pan",
"brasero",
"brazier pot",
"bread knife",
"bread pan",
"bread machine",
"broiler pan",
"browning tray",
"burjiko",
"butane torch",
"butcher block",
"butcher paper",
"butter churn",
"butter curler",
"caddy spoon",
"cake and pie server",
"cake pan",
"can opener",
"candy thermometer",
"carbon steel pan",
"casserole",
"casserole pan",
"cassole",
"cast iron skillet",
"cast iron dutch oven",
"chakla",
"chambers stove",
"cheesecloth",
"cheesemelter",
"cheese knife",
"cheese scoop",
"cherry pitter",
"chestnut pan",
"chinoise",
"chip pan",
"chocolatera",
"churchkey",
"cocktail stick",
"coffee filter",
"coffeemaker",
"colander",
"convection microwave",
"cookie cutter",
"cookie press",
"cookie sheet",
"cooking pot",
"cooking sheet",
"cooling racks",
"copper hand hammered brazing pot",
"copper sauce pan",
"corkscrew",
"crab cracker",
"crepe pan",
"cutting board",
"chorkor oven",
"clean-burning stove",
"clome oven",
"coffee percolator",
"coffeemaker",
"comal (cookware)",
"combi steamer",
"communal oven",
"community Cooker",
"convection microwave",
"convection oven",
"cook stove",
"corn roaster",
"crepe maker",
"diffuser (heat)",
"double boiler",
"doufeu",
"dough blender",
"dough scraper",
"dutch oven",
"deep fryer",
"eggbeater",
"egg piercer",
"egg poacher",
"egg separator",
"egg slicer",
"egg timer",
"electric kettle",
"electric water boiler",
"embossing mat",
"earth oven",
"ecoZoom",
"electric cooker",
"electric stove",
"energy regulator",
"fillet knife",
"fish scalar",
"fish slice (kitchen utensil)",
"flat iron grill pan",
"flat rack",
"flesh-hook",
"flour sifter",
"fondue pot",
"food mill",
"food processor",
"frosting spatula",
"frying pan",
"frying skillet",
"funnel",
"field kitchen",
"fire pot",
"flattop grill",
"food steamer",
"foukou",
"fufu Machine",
"gas stove",
"garlic press",
"glass baking pan",
"gratine pan",
"grapefruit knife",
"grater",
"gravy strainer",
"greaseproof paper",
"griddle",
"grill pan",
"hand held electric mixer",
"herb chopper",
"halogen oven",
"haybox",
"hibachi",
"hoang Cam stove",
"hobo stove",
"horno",
"hot Box (appliance)",
"hot plate",
"induction cooking",
"juicer",
"karahi",
"kettle",
"kitchen utensil",
"kitchen knife",
"kamado",
"kettle",
"kitchen oven",
"kitchen stove",
"kitchener range",
"krampouz",
"kujiejun",
"kyoto box",
"ladle",
"lame",
"lemon reamer",
"lemon squeezer",
"loaf pan",
"lobster pick",
"lo trau",
"mandoline",
"mated colander pot",
"measuring cup",
"measuring jug",
"measuring spoon",
"meat grinder",
"meat tenderizer",
"meat thermometer",
"meatloaf pan",
"melon baller",
"mezzaluna",
"mortar and pestle",
"microplane",
"microwave",
"microwave oven",
"milk watcher",
"mouli grater",
"mushroom cloth",
"masonry oven",
"mess kit",
"microwave oven",
"multi-fuel stove",
"nonadjustable V-rack",
"nonstick skillet",
"nutcracker",
"nutmeg grater",
"nomiku",
"omelette pan",
"oven",
"oven bag",
"oven glove",
"oXO (brand)",
"p-38 can opener",
"paella pan",
"palayok",
"parchment paper",
"pasta spoon",
"pastry bag",
"pastry blender",
"pastry brush",
"pastry wheel",
"peel (tool)",
"peeler",
"pepper mill",
"pie bird",
"pie pan",
"pizza cutter",
"plastic wrap",
"potato masher",
"potato ricer",
"pot boiler",
"pot holder",
"pothook",
"poultry shears",
"pressure cooker",
"pudding basin",
"pudding cloth",
"pyrex baking dish",
"popcorn maker",
"primus stove",
"Ramekin",
"rice spoon",
"ricer",
"rice cooker",
"roasting jack",
"roasting pan",
"roasting pan with high cover",
"roasting rack",
"roller docker",
"rolling pin",
"rondeau",
"round cake pan",
"red Cross stove",
"reflector oven",
"remoska",
"rice cooker",
"rice polisher",
"roasting jack",
"rocket mass heater",
"rocket stove",
"russian oven",
"salad spoon",
"salt and pepper shakers",
"saran (plastic)",
"saucier",
"saute pan",
"saucepan",
"sauteuse pan",
"scales",
"scissors",
"scoop",
"scotch hands",
"scraper (kitchen)",
"serving spoon",
"serving tongs",
"shellfish scraper",
"sieve",
"silpat",
"skewer",
"skillet",
"skimmer",
"slotted spoon",
"soup ladle",
"spatula",
"spider",
"splatter screen",
"springform pan",
"spurtle",
"Stainless steel pan",
"Stir-fry pan",
"stockpot",
"sugar nips",
"sugar spoon",
"sugar thermometer",
"sugar tong",
"sujeo",
"sabbath mode",
"salamander broiler",
"samovar",
"sandwich toaster",
"self-cleaning oven",
"shichirin",
"sigri (stove)",
"slow cooker",
"solar cooker",
"soy milk maker",
"stove",
"susceptor",
"tablespoon",
"tajine",
"tamis",
"tava",
"tea infuser",
"teflon coated frying pan",
"timbale (food)",
"tin foil",
"tin opener",
"toaster oven",
"tomato knife",
"tongs",
"trivection oven",
"trivet",
"trussing needle",
"two burner griddle pan",
"tabun oven",
"tandoor",
"tangia",
"tea stove",
"thermal immersion circulator",
"toaster",
"tommy cooker",
"trojan Room coffee pot",
"turkey fryer",
"vegetable peeler",
"vertical rack",
"vacuum fryer",
"wax paper",
"whisk",
"wok",
"wonder pot",
"wooden spoon",
"waffle iron",
"wet grinder",
"wood-burning stove",
"wood-fired oven",
"zester"


]


	